### ISSUE TITLE
Cortex System

### ISSUE THREAD

**Issue by RustySellsword** [isaaclyman/ttrpg-guide#1]
**This RPG is not defunct (Yes/No):** No

**This RPG is well known (Yes/No):** Yes

**RPG System Name:** Cortex

**Core Setting:** setting-agnostic

**Largest Associated Subreddit:**
R/CortexRPG

**Claim to Fame:**
System used for licensed RPGs including Firefly, Marvel Heroic, Smallville, Dragon Prince

**Core Mechanic:**
Dice pools that include dice from each appropriate trait. Roll and add two results together to beat a difficulty number. 

**Core PDFs:**

**System Reference Document:**
CortexRPG.com

**Most Famous Property:**
Marvel, Firefly

**Amount of Crunch:**
Medium to low crunch

**Owner:**
Dire Wolf Digital

**Timeline:**
Serenity RPG 2005, Marvel 2011, Cortex Prime
game Handbook (fully modular generic toolkit) 2020

**Comment by isaaclyman** [comment]
Added in commit 360b321. Thanks!
