### ISSUE TITLE
[Add RPG]  Forbidden Lands is missing for Year Zero System

### ISSUE THREAD

**Issue by Eleksar387** [isaaclyman/ttrpg-guide#13]
They have a popular subreddit /r/ForbiddenLands/ (6.5K users) and Discord https://discord.com/invite/q2vPPbMVvg (only 500 members)

https://www.drivethrurpg.com/en/product/258593/forbidden-lands-core-game (Currently at 12.99)

2018 (published)

**Comment by isaaclyman** [comment]
Thanks, added.
