### ISSUE TITLE
[Add RPG] Symbaroum

### ISSUE THREAD

**Issue by Nobleonekenobi** [isaaclyman/ttrpg-guide#14]
System: Standard RPG System

**Core Setting:**

  Gritty Realism, Dark Fantasy Setting
**Claim to Fame:**

 D20 Roll Under
**Core Mechanic:**

**Core PDFs:**

**License:**

**System Reference Document:**

Symbaroum

Medium Crunch

Free League

2016

<!-- What does the game feel like to play? It is a Gritty Realism. Death is quick and fantasy setting is unique.

**Comment by isaaclyman** [comment]
Added. Thank you.
