### ISSUE TITLE
Worlds Without Number

### ISSUE THREAD

**Issue by MrCauli** [isaaclyman/ttrpg-guide#17]
**This RPG is still actively sold and promoted (Yes/No):**
YES

Ability checks: 2d6
Attack rolls:d20

Unknown

https://www.drivethrurpg.com/en/product/348809/worlds-without-number-free-edition

Slightly. 

Publisher:
Sine nomine Publishing

Creation:
Before May 2017

How it feels to play:
fast-paced; rules light; tuneable difficulty; low-prep; combat as last resort

**Comment by isaaclyman** [comment]
This is already in the list under *Stars Without Number*.

**Comment by MrCauli** [comment]
> This is already in the list under _Stars Without Number_.

It's a somewhat different system though.

**Comment by isaaclyman** [comment]
Pops right up for me.

<img width="605" alt="Screenshot 2024-11-19 at 9 56 22 AM" src="https://github.com/user-attachments/assets/d9cd2ae1-0d53-47b9-af27-a4ef1c2d3ab7">

In what way is it different?

**Comment by MrCauli** [comment]
It's a medieval fantasy, not science fantasy/scifi. Also has a different community.
