### ISSUE TITLE
Open licensed column

### ISSUE THREAD

**Issue by Zireael07** [isaaclyman/ttrpg-guide#2]
**What's your idea?**

The column should specify the license the game is under. Currently it seems to link to the site/SRD if it exists, but does not mention the actual license

**Why is this important to you?**
People should be aware of what license the game is under so that they can more easily conform to it when modifying stuff

**Comment by isaaclyman** [comment]
Agreed. This information can be hard to find for smaller games—for example, after a bunch of research, I still don't know if it's legal to make and sell a setting/adventure for Dread.

**Comment by isaaclyman** [comment]
The License column now includes better information about the game's license and its permissiveness.

**Comment by Zireael07** [comment]
Okay, so continuing: Cortex Prime seems to have a community license but it's been shuffled to somewhere inaccessible (used to be on their site, now only a copy on Google Drive survives https://drive.google.com/drive/folders/18O1siivna9SKqocztcG0q2JmkA6InIR1 )

Burning Wheel indeed does not have a licence that I know of and Risus is just a "do whatever you want" thing

**Comment by isaaclyman** [comment]
Yeah, I found several links to the Cortex Prime community license but none of them work. Out of an abundance of caution I'm not listing licenses that might have been affected by a transfer of IP or might no longer be in effect. That Google Drive folder doesn't have a license in it, just some images.

I know Risus has a lot of community-made content, but I couldn't find any actual documentation of their policies, so again, being cautious on that one.
