### ISSUE TITLE
[Add RPG] Traveller

### ISSUE THREAD

**Issue by code-monki** [isaaclyman/ttrpg-guide#4]
**This RPG is still actively sold and promoted (Yes/No):** 
Yes

**Evidence of popularity:**
https://discord.gg/hvUJEpU

**RPG System Name:**
Traveller

**Core Setting:**
3rd Imperium, Shattered Imperium

**Claim to Fame:**

One of the oldest SciFi RPG (only preceded by Metamorphosis Alpha)
Rich life paths

**Core Mechanic:**

1d6/2d6/3d6

**Core PDFs:**
https://preview.drivethrurpg.com/en/product/150646/t5-traveller5-core-rules-3-book-set

**System Reference Document:**
https://preview.drivethrurpg.com/en/product/355200/classic-traveller-facsimile-edition

**Most Famous Property:**

Firefly (inspired by Traveller campaigns according to Joss Whedon)

**Amount of Crunch:**

Can vary from rules-light to very crunchy depending on what the GM wants to do.

**Owner:**

Far Future Enterprises (Marc Miller)

**Timeline:**

Orig. Ed. 1977
Latest Ed. 2006 (last update 2019)
3rd Imperium / Fifth Frontier War are / Shattered Imperium are the most popular although most GMs create their own settings (IMTU - In My Traveller Universe)

**Gameplay:**

Depends on the GM. All of the example tags listed (action bite-sized, cinematic, dark, deadly, drama, fast-paced, gritty, heist, humor, literary, pulpy, tactical, toolkit) are applicable.

**NOTES**:

See [Traveller Community Portal](https://wiki.travellerrpg.com/Traveller:Community_Portal) for other publishers.

**Comment by isaaclyman** [comment]
Thanks for the submission.

"Depends on the GM" isn't helpful here. If someone is considering a bunch of different RPGs, what tags would help them distinguish Traveller from the other options?

How crunchy is it if you play RAW, without skipping or ignoring any rules?

**Comment by isaaclyman** [comment]
Added.

Each system gets one row in a table, so everything has to have a hard-and-fast answer, even though all RPGs vary depending on how you run them. Reddit threads indicate it's a little crunchier than Stars Without Number, which I've got listed as "medium crunch," so Traveller is getting "medium-high."

**Comment by code-monki** [comment]
Cool!

On Mar 21, 2024, at 3:22 PM, Isaac Lyman ***@***.***> wrote:



Added.

Each system gets one row in a table, so everything has to have a hard-and-fast answer, even though all RPGs vary depending on how you run them. Reddit threads indicate it's a little crunchier than Stars Without Number, which I've got listed as "medium crunch," so Traveller is getting "medium-high."
