### ISSUE TITLE
Adding clarity to licensing

### ISSUE THREAD

**Issue by amazingrando** [isaaclyman/ttrpg-guide#6]
**What's your idea?**

Licensing for RPGs has a lot of factors. For example, is a game licensed using the OGL, a Creative Commons license, or the ORC license?

Also how much of the game is licensed? Fate and Pathfinder have everything under their licenses, while D&D only licenses a little for 5e. 

**Why is this important to you?**

The nuance of licensing impacts what the community and individuals can do with it.

**Comment by isaaclyman** [comment]
Duplicate of #2.

**Comment by isaaclyman** [comment]
The License column now includes more detailed information.
