### ISSUE TITLE
Crunch level should be user voted

### ISSUE THREAD

**Issue by amazingrando** [isaaclyman/ttrpg-guide#7]
**What's your idea?**

The definition of crunch varies from person to person, so why not lean on the wisdom of crowds?

Each game should have a way to rate a game's crunch as either low, medium, or high. Then this data could be displayed to inform people. 

**Why is this important to you?**

It would be a more accurate way of determining a game's crunch level.

**Comment by isaaclyman** [comment]
I can't begin to describe how much more work that is than a static website.
