### ISSUE TITLE
Allow null value for "largest_subreddit" for popular games that don't have dedicated subreddits

### ISSUE THREAD

**Issue by AugFJTan** [isaaclyman/ttrpg-guide#8]
**What's your idea?**
Allow null value for "largest_subreddit" for certain games that don't have dedicated subreddits, but are widely discussed online (on r/rpg at least).

**Why is this important to you?**
Not all games have dedicated subreddits, but are worth highlighting if they have a decent following online. Games such as Alice is Missing are usually brought up on r/rpg and discussed there.

**Comment by isaaclyman** [comment]
I've updated the code so a `null` value in the subreddit fields won't crash the page or anything. Additionally, if the game has a Discord that's larger than its (possibly nonexistent) subreddit, that will be used for the initial sort. Closing this issue as complete.
