### ISSUE TITLE
Lancer

### ISSUE THREAD

**Issue by racercowan** [isaaclyman/ttrpg-guide#9]
**This RPG is still actively sold and promoted (Yes/No):** Yes

**Evidence of popularity:** [Lancer Subreddit](https://www.reddit.com/r/LancerRPG/) (32k members), [Pilot Net discord](https://discord.com/invite/lancer) (40k members)

**RPG System Name:** Lancer

**Core Setting:** Science Fiction

**Claim to Fame:** Mech customization with swappable systems (for both Player PCs and GM NPCs), largely played online with VTTs and [fan-made companion website](https://compcon.app)

**Core Mechanic:** 1d20+modifier (max 6)±1d6 ≥ 10, 20, or enemy value

**Core PDFs:** [Core Rulebook](https://massif-press.itch.io/corebook-pdf) ($25)

**System Reference Document:** [Free Core Rulebook](https://massif-press.itch.io/corebook-pdf-free) (base rules and player content only)

**Most Famous Property:** Itself

**Amount of Crunch:** Medium-High Crunch in combat, Low Crunch outside of combat

**Owner:** Massif Press

**Timeline:** 2019 (Published)

**Gameplay:** Combat is strict and tactical and can feel almost puzzle-like at times, narrative rules are very loose and freeform

**Comment by racercowan** [comment]
To condense the "Claim to Fame" into something more compact to fit the table, maybe "customizable mechs" and "online companion"?

**Comment by isaaclyman** [comment]
Thanks for all the detail. New entry is going live right now.
